// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAloR8XP25oPnpstd0gWItE-i_eQdGfQgA',
    appId: '1:1059718279966:web:5e7a6941f3452ef3d1cf0f',
    messagingSenderId: '1059718279966',
    projectId: 'findmybag-7efe7',
    authDomain: 'findmybag-7efe7.firebaseapp.com',
    storageBucket: 'findmybag-7efe7.appspot.com',
    measurementId: 'G-BZXE8QL5Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUCsOB1WHXItVLvdKJ5a2nrrQcJUPdSVQ',
    appId: '1:1059718279966:android:36d63aa13d52f1a1d1cf0f',
    messagingSenderId: '1059718279966',
    projectId: 'findmybag-7efe7',
    storageBucket: 'findmybag-7efe7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAf8rTLC7DK38j7zVjVKNbUiXph3cLGfk',
    appId: '1:1059718279966:ios:7f4e8335ef79c7a0d1cf0f',
    messagingSenderId: '1059718279966',
    projectId: 'findmybag-7efe7',
    storageBucket: 'findmybag-7efe7.appspot.com',
    iosClientId: '1059718279966-j3rkiq7j7lvgpgsc43lj07h42d02mlas.apps.googleusercontent.com',
    iosBundleId: 'com.example.findmybag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAf8rTLC7DK38j7zVjVKNbUiXph3cLGfk',
    appId: '1:1059718279966:ios:7f4e8335ef79c7a0d1cf0f',
    messagingSenderId: '1059718279966',
    projectId: 'findmybag-7efe7',
    storageBucket: 'findmybag-7efe7.appspot.com',
    iosClientId: '1059718279966-j3rkiq7j7lvgpgsc43lj07h42d02mlas.apps.googleusercontent.com',
    iosBundleId: 'com.example.findmybag',
  );
}
